# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShishaTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShishaTime
  pod 'Alamofire'
  pod 'GoogleSignIn'
  pod 'SDWebImage'
end
